version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
     - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
      
volumes:
    postgres:
    
networks:
  postgres:
    driver: bridge